services:
  pingpanda:
    image: ghcr.io/kingpin/pingpanda:latest # Use the latest image
    container_name: pingpanda # Container name
    environment:
      - DOMAIN=google.com # Domain to check fns for 
      - PING_IP=8.8.8.8 # IP to ping
      - LOG_DIR=/logs # Directory to store logs
      - LOG_TO_TERMINAL=true # Log to terminal
      - LOG_TO_FILE=true # Log to file
      - INTERVAL=15 # Interval in seconds
      - VERBOSE=true # Enable verbose logging
      - MAX_LOG_SIZE=1048576 # Maximum log size in bytes
      - LOG_BACKUP_COUNT=5 # Number of backup logs to keep
      - ENABLE_PING=true # Enable ping checks
      - ENABLE_DNS=true # Enable DNS checks
      - ENABLE_WEBSITE_CHECK=true # Enable website check
      - CHECK_WEBSITE=https://www.google.com # Website to check
      - RETRY_COUNT=1 # Number of retries for checks
      - SUCCESS_HTTP_CODES=200,201,202 # HTTP status codes considered successful
    volumes:
      - ./logs:/logs # Mount logs directory
    restart: unless-stopped # Restart unless stopped